/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.ensemble.interrogamefscerev;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InterrogaMefScerevSoap", targetNamespace = "http://InterrogaMefScerev.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InterrogaMefScerevSoap {


    /**
     * 
     * @param cf
     * @return
     *     returns it.csi.aura.auraws.services.central.interrogamefscerev.InterrogaMefScerevResult
     */
    @WebMethod(operationName = "InterrogaMefScerev", action = "http://InterrogaMefScerev.central.services.auraws.aura.csi.it/AURA.WS.InterrogaMefScerev.InterrogaMefScerev")
    @WebResult(name = "InterrogaMefScerevResp", targetNamespace = "http://InterrogaMefScerev.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "InterrogaMefScerev", targetNamespace = "http://InterrogaMefScerev.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.interrogamefscerev.InterrogaMefScerev")
    @ResponseWrapper(localName = "InterrogaMefScerevResponse", targetNamespace = "http://InterrogaMefScerev.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.interrogamefscerev.InterrogaMefScerevResponse")
    public InterrogaMefScerevResult interrogaMefScerev(
        @WebParam(name = "CF", targetNamespace = "http://InterrogaMefScerev.central.services.auraws.aura.csi.it")
        String cf);

}
