/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.find;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AnagrafeFind", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it")
public class AnagrafeFind
    extends Service
{

    private final static URL ANAGRAFEFIND_WSDL_LOCATION = null;
    private final static QName ANAGRAFEFIND_QNAME = new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFind");

//    static {
//        URL url = null;
//        String urlWSDL = "https://portale.ruparpiemonte.it/sanitxens/aura/AURA.WS.AnagrafeFind.cls?WSDL";
//        try {
//            URL baseUrl;
//            baseUrl = AnagrafeFind.class.getResource(".");
//            url = new URL(baseUrl, urlWSDL);
//        } catch (MalformedURLException e) {
//        }
//        ANAGRAFEFIND_WSDL_LOCATION = url;
//    }

//    public AnagrafeFind() {
//        super(__getWsdlLocation(), ANAGRAFEFIND_QNAME);
//    }

//    public AnagrafeFind(WebServiceFeature... features) {
//        super(__getWsdlLocation(), ANAGRAFEFIND_QNAME, features);
//    }
//
    public AnagrafeFind(URL wsdlLocation) {
        super(wsdlLocation, ANAGRAFEFIND_QNAME);
    }

    public AnagrafeFind(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANAGRAFEFIND_QNAME, features);
    }

    public AnagrafeFind(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnagrafeFind(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    public AnagrafeFind(String string) {
    	super(__getWsdlLocation(string), ANAGRAFEFIND_QNAME);
	}
    
    /**
     * 
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap() {
        return super.getPort(new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFindSoap"), AnagrafeFindSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFindSoap"), AnagrafeFindSoap.class, features);
    }

//    private static URL __getWsdlLocation() {
//      
//        return ANAGRAFEFIND_WSDL_LOCATION;
//    }
    
    private static URL __getWsdlLocation(String endpoint) {
    	URL baseUrl;
    	URL url = null;
		baseUrl = AnagrafeFind.class.getResource(".");
		try {
			url = new URL(baseUrl, endpoint+"?WSDL");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return url;
    }

}
