/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
/**
 * PolicyEnforcerBaseService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package it.csi.scerev.scerevserviziesterni.iride.base;

public interface PolicyEnforcerBaseService extends java.rmi.Remote {
    public it.csi.scerev.scerevserviziesterni.iride.base.Identita identificaUserPassword(java.lang.String in0, java.lang.String in1) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.MalformedUsernameException, it.csi.scerev.scerevserviziesterni.iride.base.AuthException, it.csi.scerev.scerevserviziesterni.iride.base.IdProviderNotFoundException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public it.csi.scerev.scerevserviziesterni.iride.base.Identita identificaCertificato(byte[] in0) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.CertRevokedException, it.csi.scerev.scerevserviziesterni.iride.base.CertOutsideValidityException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.IdProviderNotFoundException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public it.csi.scerev.scerevserviziesterni.iride.base.Identita identificaUserPasswordPIN(java.lang.String in0, java.lang.String in1, java.lang.String in2) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.MalformedUsernameException, it.csi.scerev.scerevserviziesterni.iride.base.AuthException, it.csi.scerev.scerevserviziesterni.iride.base.IdProviderNotFoundException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public boolean isPersonaAutorizzataInUseCase(it.csi.scerev.scerevserviziesterni.iride.base.Identita in0, it.csi.scerev.scerevserviziesterni.iride.base.UseCase in1) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.IdentitaNonAutenticaException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchUseCaseException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchApplicationException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public it.csi.scerev.scerevserviziesterni.iride.base.UseCase[] findUseCasesForPersonaInApplication(it.csi.scerev.scerevserviziesterni.iride.base.Identita in0, it.csi.scerev.scerevserviziesterni.iride.base.Application in1) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.IdentitaNonAutenticaException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchApplicationException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public boolean isIdentitaAutentica(it.csi.scerev.scerevserviziesterni.iride.base.Identita in0) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public java.lang.String getInfoPersonaInUseCase(it.csi.scerev.scerevserviziesterni.iride.base.Identita in0, it.csi.scerev.scerevserviziesterni.iride.base.UseCase in1) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.IdentitaNonAutenticaException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchUseCaseException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchApplicationException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public it.csi.scerev.scerevserviziesterni.iride.base.Ruolo[] findRuoliForPersonaInUseCase(it.csi.scerev.scerevserviziesterni.iride.base.Identita in0, it.csi.scerev.scerevserviziesterni.iride.base.UseCase in1) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.IdentitaNonAutenticaException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchUseCaseException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchApplicationException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public it.csi.scerev.scerevserviziesterni.iride.base.Ruolo[] findRuoliForPersonaInApplication(it.csi.scerev.scerevserviziesterni.iride.base.Identita in0, it.csi.scerev.scerevserviziesterni.iride.base.Application in1) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.IdentitaNonAutenticaException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchApplicationException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public java.lang.String getInfoPersonaSchema(it.csi.scerev.scerevserviziesterni.iride.base.Ruolo in0) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.BadRuoloException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public it.csi.scerev.scerevserviziesterni.iride.base.Actor[] findActorsForPersonaInApplication(it.csi.scerev.scerevserviziesterni.iride.base.Identita in0, it.csi.scerev.scerevserviziesterni.iride.base.Application in1) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.IdentitaNonAutenticaException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchApplicationException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public it.csi.scerev.scerevserviziesterni.iride.base.Actor[] findActorsForPersonaInUseCase(it.csi.scerev.scerevserviziesterni.iride.base.Identita in0, it.csi.scerev.scerevserviziesterni.iride.base.UseCase in1) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.IdentitaNonAutenticaException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchUseCaseException, it.csi.scerev.scerevserviziesterni.iride.base.NoSuchApplicationException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
    public boolean isPersonaInRuolo(it.csi.scerev.scerevserviziesterni.iride.base.Identita in0, it.csi.scerev.scerevserviziesterni.iride.base.Ruolo in1) throws java.rmi.RemoteException, it.csi.scerev.scerevserviziesterni.iride.base.UnrecoverableException, it.csi.scerev.scerevserviziesterni.iride.base.IdentitaNonAutenticaException, it.csi.scerev.scerevserviziesterni.iride.base.SystemException, it.csi.scerev.scerevserviziesterni.iride.base.BadRuoloException, it.csi.scerev.scerevserviziesterni.iride.base.InternalException;
}
