/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevaurabatch.aura.getdistretto;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetDistrettoSoap", targetNamespace = "http://GetDistretto.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetDistrettoSoap {


    /**
     * 
     * @return
     *     returns it.csi.aura.auraws.services.central.getdistretto.GetDistrettoResult
     */
    @WebMethod(operationName = "GetDistretto", action = "http://GetDistretto.central.services.auraws.aura.csi.it/AURA.WS.GetDistretto.GetDistretto")
    @WebResult(name = "GetDistrettoResp", targetNamespace = "http://GetDistretto.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "GetDistretto", targetNamespace = "http://GetDistretto.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.getdistretto.GetDistretto")
    @ResponseWrapper(localName = "GetDistrettoResponse", targetNamespace = "http://GetDistretto.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.getdistretto.GetDistrettoResponse")
    public GetDistrettoResult getDistretto();

}
