/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevlibbatch.opessan.services.opessanws.opessan;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MassimaliMedici", targetNamespace = "http://opessan.opessanws.services.csi.it/", wsdlLocation = "https://tst-applogic.reteunitaria.piemonte.it:1449/opessanwsj/services/massimaliMediciUserTkn?wsdl")
public class MassimaliMedici_Service
    extends Service
{

    private final static URL MASSIMALIMEDICI_WSDL_LOCATION;
    private final static WebServiceException MASSIMALIMEDICI_EXCEPTION;
    private final static QName MASSIMALIMEDICI_QNAME = new QName("http://opessan.opessanws.services.csi.it/", "MassimaliMedici");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://tst-applogic.reteunitaria.piemonte.it:1449/opessanwsj/services/massimaliMediciUserTkn?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MASSIMALIMEDICI_WSDL_LOCATION = url;
        MASSIMALIMEDICI_EXCEPTION = e;
    }

    public MassimaliMedici_Service() {
        super(__getWsdlLocation(), MASSIMALIMEDICI_QNAME);
    }
//
//    public MassimaliMedici_Service(WebServiceFeature... features) {
//        super(__getWsdlLocation(), MASSIMALIMEDICI_QNAME, features);
//    }
//
//    public MassimaliMedici_Service(URL wsdlLocation) {
//        super(wsdlLocation, MASSIMALIMEDICI_QNAME);
//    }
//
//    public MassimaliMedici_Service(URL wsdlLocation, WebServiceFeature... features) {
//        super(wsdlLocation, MASSIMALIMEDICI_QNAME, features);
//    }
//
//    public MassimaliMedici_Service(URL wsdlLocation, QName serviceName) {
//        super(wsdlLocation, serviceName);
//    }
//
//    public MassimaliMedici_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
//        super(wsdlLocation, serviceName, features);
//    }

    /**
     * 
     * @return
     *     returns MassimaliMedici
     */
    @WebEndpoint(name = "MassimaliMediciCXFImplPort")
    public MassimaliMedici getMassimaliMediciCXFImplPort() {
        return super.getPort(new QName("http://opessan.opessanws.services.csi.it/", "MassimaliMediciCXFImplPort"), MassimaliMedici.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MassimaliMedici
     */
    @WebEndpoint(name = "MassimaliMediciCXFImplPort")
    public MassimaliMedici getMassimaliMediciCXFImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://opessan.opessanws.services.csi.it/", "MassimaliMediciCXFImplPort"), MassimaliMedici.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MASSIMALIMEDICI_EXCEPTION!= null) {
            throw MASSIMALIMEDICI_EXCEPTION;
        }
        return MASSIMALIMEDICI_WSDL_LOCATION;
    }

}
