/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevlibbatch.opessan.services.opessanws.opessan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MassimaliMedici", targetNamespace = "http://opessan.opessanws.def.csi.it/")
@XmlSeeAlso({
	it.csi.scerev.scerevlibbatch.opessan.def.opessanws.opessan.ObjectFactory.class,
	it.csi.scerev.scerevlibbatch.opessan.dto.opessanws.opessan.common.request.ObjectFactory.class,
	it.csi.scerev.scerevlibbatch.opessan.dto.opessanws.opessan.common.response.ObjectFactory.class
})
public interface MassimaliMedici {


    /**
     * 
     * @param arg0
     * @return
     *     returns it.csi.scerev.scerevlibbatch.opessan.def.opessanws.opessan.GetMassimaliMedicoResponse.Return
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMassimaliMedico", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.scerev.scerevlibbatch.opessan.def.opessanws.opessan.GetMassimaliMedico")
    @ResponseWrapper(localName = "getMassimaliMedicoResponse", targetNamespace = "http://opessan.opessanws.def.csi.it/", className = "it.csi.scerev.scerevlibbatch.opessan.def.opessanws.opessan.GetMassimaliMedicoResponse")
    public it.csi.scerev.scerevlibbatch.opessan.def.opessanws.opessan.GetMassimaliMedicoResponse.Return getMassimaliMedico(
        @WebParam(name = "arg0", targetNamespace = "")
        it.csi.scerev.scerevlibbatch.opessan.def.opessanws.opessan.GetMassimaliMedico.Arg0 arg0);

}
