/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.getambito;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetAmbito", targetNamespace = "http://GetAmbito.central.services.auraws.aura.csi.it")
public class GetAmbito_Service
    extends Service
{

    private static final URL GETAMBITO_WSDL_LOCATION = null;
    private final static QName GETAMBITO_QNAME = new QName("http://GetAmbito.central.services.auraws.aura.csi.it", "GetAmbito");

//    static {
//        URL url = null;
//        String urlWSDL = "http://10.102.40.77:57772/sanitxens_t1/AURA.WS.GetAmbito.cls?WSDL";
//        try {
//            URL baseUrl;
//            baseUrl = GetAmbito_Service.class.getResource(".");
//            url = new URL(baseUrl, urlWSDL);
//        } catch (MalformedURLException e) {
//        }
//        GETAMBITO_WSDL_LOCATION = url;
//    }
//
//    public GetAmbito_Service() {
//        super(__getWsdlLocation(), GETAMBITO_QNAME);
//    }
//
//    public GetAmbito_Service(WebServiceFeature... features) {
//        super(__getWsdlLocation(), GETAMBITO_QNAME, features);
//    }

    public GetAmbito_Service(URL wsdlLocation) {
        super(wsdlLocation, GETAMBITO_QNAME);
    }

    public GetAmbito_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETAMBITO_QNAME, features);
    }

    public GetAmbito_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetAmbito_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    public GetAmbito_Service(String string) {
    	super(__getWsdlLocation(string), GETAMBITO_QNAME);
	}

	/**
     * 
     * @return
     *     returns GetAmbitoSoap
     */
    @WebEndpoint(name = "GetAmbitoSoap")
    public GetAmbitoSoap getGetAmbitoSoap() {
        return super.getPort(new QName("http://GetAmbito.central.services.auraws.aura.csi.it", "GetAmbitoSoap"), GetAmbitoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetAmbitoSoap
     */
    @WebEndpoint(name = "GetAmbitoSoap")
    public GetAmbitoSoap getGetAmbitoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://GetAmbito.central.services.auraws.aura.csi.it", "GetAmbitoSoap"), GetAmbitoSoap.class, features);
    }

    private static URL __getWsdlLocation(String endpoint) {
    	URL baseUrl;
    	URL url = null;
		baseUrl = GetAmbito_Service.class.getResource(".");
		try {
			url = new URL(baseUrl, endpoint+"?WSDL");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return url;

    }

}
