/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.getUltimoMovimentoDiRevoca;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "getUltimoMovimentoDiRevocaSoap", targetNamespace = "http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetUltimoMovimentoDiRevocaSoap {


    /**
     * 
     * @param pInput
     * @return
     *     returns it.csi.scerev.scerevserviziesterni.aura.getUltimoMovimentoDiRevoca.Response
     */
    @WebMethod(action = "http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it/AURA.WS.getUltimoMovimentoDiRevoca.getUltimoMovimentoDiRevoca")
    @WebResult(name = "getUltimoMovimentoDiRevocaResult", targetNamespace = "http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "getUltimoMovimentoDiRevoca", targetNamespace = "http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it", className = "it.csi.scerev.scerevserviziesterni.aura.getUltimoMovimentoDiRevoca.GetUltimoMovimentoDiRevoca")
    @ResponseWrapper(localName = "getUltimoMovimentoDiRevocaResponse", targetNamespace = "http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it", className = "it.csi.scerev.scerevserviziesterni.aura.getUltimoMovimentoDiRevoca.GetUltimoMovimentoDiRevocaResponse")
    public Response getUltimoMovimentoDiRevoca(
        @WebParam(name = "pInput", targetNamespace = "http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it")
        Request pInput);

}
