/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.getUltimoMovimentoDiRevoca;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.csi.scerev.scerevserviziesterni.aura.getambito.GetAmbito_Service;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "getUltimoMovimentoDiRevoca", targetNamespace = "http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it")
public class GetUltimoMovimentoDiRevoca_Service
    extends Service
{

    private final static URL GETULTIMOMOVIMENTODIREVOCA_WSDL_LOCATION = null;
    private final static QName GETULTIMOMOVIMENTODIREVOCA_QNAME = new QName("http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it", "getUltimoMovimentoDiRevoca");

//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("http://10.102.40.77:57772/sanitxens_t3/AURA.WS.getUltimoMovimentoDiRevoca.cls?wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        GETULTIMOMOVIMENTODIREVOCA_WSDL_LOCATION = url;
//        GETULTIMOMOVIMENTODIREVOCA_EXCEPTION = e;
//    }
//
//    public GetUltimoMovimentoDiRevoca_Service() {
//        super(__getWsdlLocation(), GETULTIMOMOVIMENTODIREVOCA_QNAME);
//    }
//
//    public GetUltimoMovimentoDiRevoca_Service(WebServiceFeature... features) {
//        super(__getWsdlLocation(), GETULTIMOMOVIMENTODIREVOCA_QNAME, features);
//    }

    public GetUltimoMovimentoDiRevoca_Service(URL wsdlLocation) {
        super(wsdlLocation, GETULTIMOMOVIMENTODIREVOCA_QNAME);
    }

    public GetUltimoMovimentoDiRevoca_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETULTIMOMOVIMENTODIREVOCA_QNAME, features);
    }

    public GetUltimoMovimentoDiRevoca_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetUltimoMovimentoDiRevoca_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }
    
    public GetUltimoMovimentoDiRevoca_Service(String string) {
    	super(__getWsdlLocation(string), GETULTIMOMOVIMENTODIREVOCA_QNAME);
	}


    /**
     * 
     * @return
     *     returns GetUltimoMovimentoDiRevocaSoap
     */
    @WebEndpoint(name = "getUltimoMovimentoDiRevocaSoap")
    public GetUltimoMovimentoDiRevocaSoap getGetUltimoMovimentoDiRevocaSoap() {
        return super.getPort(new QName("http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it", "getUltimoMovimentoDiRevocaSoap"), GetUltimoMovimentoDiRevocaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetUltimoMovimentoDiRevocaSoap
     */
    @WebEndpoint(name = "getUltimoMovimentoDiRevocaSoap")
    public GetUltimoMovimentoDiRevocaSoap getGetUltimoMovimentoDiRevocaSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://getUltimoMovimentoDiRevoca.central.services.auraws.aura.csi.it", "getUltimoMovimentoDiRevocaSoap"), GetUltimoMovimentoDiRevocaSoap.class, features);
    }

    private static URL __getWsdlLocation(String endpoint) {
    	URL baseUrl;
    	URL url = null;
		baseUrl = GetUltimoMovimentoDiRevoca_Service.class.getResource(".");
		try {
			url = new URL(baseUrl, endpoint+"?WSDL");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return url;

    }

}
