/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.getasldistrettoambito;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetASLDistrettoAmbitoSoap", targetNamespace = "http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetASLDistrettoAmbitoSoap {


    /**
     * 
     * @param comuneDesc
     * @param tipologiaMedico
     * @return
     *     returns it.csi.aura.auraws.services.central.getasldistrettoambito.ASLDistrettoAmbitoResponse
     */
    @WebMethod(operationName = "GetASLDistrettoAmbito", action = "http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it/AURA.WS.GetASLDistrettoAmbito.GetASLDistrettoAmbito")
    @WebResult(name = "ASLDistrettoAmbitoResp", targetNamespace = "http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "GetASLDistrettoAmbito", targetNamespace = "http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.getasldistrettoambito.GetASLDistrettoAmbito")
    @ResponseWrapper(localName = "GetASLDistrettoAmbitoResponse", targetNamespace = "http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.getasldistrettoambito.GetASLDistrettoAmbitoResponse")
    public ASLDistrettoAmbitoResponse getASLDistrettoAmbito(
        @WebParam(name = "comuneDesc", targetNamespace = "http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it")
        String comuneDesc,
        @WebParam(name = "tipologiaMedico", targetNamespace = "http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it")
        String tipologiaMedico);

}
