/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.getasldistrettoambito;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import it.csi.scerev.scerevserviziesterni.aura.setinserimentoprofiloanagrafico.SetInserimentoProfiloAnagrafico;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetASLDistrettoAmbito", targetNamespace = "http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it")
public class GetASLDistrettoAmbito_Service
    extends Service
{

    private static final URL GETASLDISTRETTOAMBITO_WSDL_LOCATION = null;
    private static final WebServiceException GETASLDISTRETTOAMBITO_EXCEPTION = new WebServiceException();
    private final static QName GETASLDISTRETTOAMBITO_QNAME = new QName("http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it", "GetASLDistrettoAmbito");

//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("file:/C:/Users/Administrator/Desktop/AURA-SER-03-GetASLDistrettoAmbito.wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        GETASLDISTRETTOAMBITO_WSDL_LOCATION = url;
//        GETASLDISTRETTOAMBITO_EXCEPTION = e;
//    }
//
//    public GetASLDistrettoAmbito_Service() {
//        super(__getWsdlLocation(), GETASLDISTRETTOAMBITO_QNAME);
//    }
//
//    public GetASLDistrettoAmbito_Service(WebServiceFeature... features) {
//        super(__getWsdlLocation(), GETASLDISTRETTOAMBITO_QNAME, features);
//    }

    public GetASLDistrettoAmbito_Service(URL wsdlLocation) {
        super(wsdlLocation, GETASLDISTRETTOAMBITO_QNAME);
    }

    public GetASLDistrettoAmbito_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETASLDISTRETTOAMBITO_QNAME, features);
    }

    public GetASLDistrettoAmbito_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetASLDistrettoAmbito_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    public GetASLDistrettoAmbito_Service(String string) {
    	super(__getWsdlLocation(string), GETASLDISTRETTOAMBITO_QNAME);
	}

	/**
     * 
     * @return
     *     returns GetASLDistrettoAmbitoSoap
     */
    @WebEndpoint(name = "GetASLDistrettoAmbitoSoap")
    public GetASLDistrettoAmbitoSoap getGetASLDistrettoAmbitoSoap() {
        return super.getPort(new QName("http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it", "GetASLDistrettoAmbitoSoap"), GetASLDistrettoAmbitoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetASLDistrettoAmbitoSoap
     */
    @WebEndpoint(name = "GetASLDistrettoAmbitoSoap")
    public GetASLDistrettoAmbitoSoap getGetASLDistrettoAmbitoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://GetASLDistrettoAmbito.central.services.auraws.aura.csi.it", "GetASLDistrettoAmbitoSoap"), GetASLDistrettoAmbitoSoap.class, features);
    }

    private static URL __getWsdlLocation(String endpoint) {
    	URL baseUrl;
    	URL url = null;
		baseUrl = GetASLDistrettoAmbito_Service.class.getResource(".");
		try {
			url = new URL(baseUrl, endpoint+"?WSDL");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return url;
    }

}
