/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.setprofilosanitario;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import it.csi.scerev.scerevserviziesterni.aura.getnumeroassistitiincaricomedico.GetNumeroAssistitiInCaricoMedico_Service;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SetProfiloSanitario", targetNamespace = "http://SetProfiloSanitario.central.services.auraws.aura.csi.it")
public class SetProfiloSanitario_Service
    extends Service
{

    private static final URL SETPROFILOSANITARIO_WSDL_LOCATION = null;
    private final static QName SETPROFILOSANITARIO_QNAME = new QName("http://SetProfiloSanitario.central.services.auraws.aura.csi.it", "SetProfiloSanitario");

//    static {
//        URL url = null;
//        String urlWSDL = "http://10.102.40.77:57772/sanitxens_t1/AURA.WS.setInserimentoProfiloAnagrafico.cls?WSDL";
//        try {
//            URL baseUrl;
//            baseUrl = GetNumeroAssistitiInCaricoMedico_Service.class.getResource(".");
//            url = new URL(baseUrl, urlWSDL);
//        } catch (MalformedURLException e) {
//        }
//        SETPROFILOSANITARIO_WSDL_LOCATION = url;
//    }
//
//    public SetProfiloSanitario_Service() {
//        super(__getWsdlLocation(), SETPROFILOSANITARIO_QNAME);
//    }
//
//    public SetProfiloSanitario_Service(WebServiceFeature... features) {
//        super(__getWsdlLocation(), SETPROFILOSANITARIO_QNAME, features);
//    }

    public SetProfiloSanitario_Service(URL wsdlLocation) {
        super(wsdlLocation, SETPROFILOSANITARIO_QNAME);
    }

    public SetProfiloSanitario_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SETPROFILOSANITARIO_QNAME, features);
    }

    public SetProfiloSanitario_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SetProfiloSanitario_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    public SetProfiloSanitario_Service(String string) {
    	super(__getWsdlLocation(string), SETPROFILOSANITARIO_QNAME);
	}

	/**
     * 
     * @return
     *     returns SetProfiloSanitarioSoap
     */
    @WebEndpoint(name = "SetProfiloSanitarioSoap")
    public SetProfiloSanitarioSoap getSetProfiloSanitarioSoap() {
        return super.getPort(new QName("http://SetProfiloSanitario.central.services.auraws.aura.csi.it", "SetProfiloSanitarioSoap"), SetProfiloSanitarioSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SetProfiloSanitarioSoap
     */
    @WebEndpoint(name = "SetProfiloSanitarioSoap")
    public SetProfiloSanitarioSoap getSetProfiloSanitarioSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://SetProfiloSanitario.central.services.auraws.aura.csi.it", "SetProfiloSanitarioSoap"), SetProfiloSanitarioSoap.class, features);
    }

    private static URL __getWsdlLocation(String endpoint) {
    	URL baseUrl;
    	URL url = null;
		baseUrl = SetProfiloSanitario_Service.class.getResource(".");
		try {
			url = new URL(baseUrl, endpoint+"?WSDL");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return url;
    }

}
