/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.setaggiornamentoprofiloanagrafico;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SetAggiornamentoProfiloAnagraficoSoap", targetNamespace = "http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SetAggiornamentoProfiloAnagraficoSoap {


    /**
     * 
     * @param datiProfilo
     * @return
     *     returns it.csi.aura.auraws.services.central.setaggiornamentoprofiloanagrafico.AggiornamentoProfiloAnagraficoRes
     */
    @WebMethod(operationName = "SetAggiornamentoProfiloAnagrafico", action = "http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it/AURA.WS.SetAggiornamentoProfiloAnagrafico.SetAggiornamentoProfiloAnagrafico")
    @WebResult(name = "SetAggiornamentoProfiloAnagraficoResult", targetNamespace = "http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "SetAggiornamentoProfiloAnagrafico", targetNamespace = "http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.setaggiornamentoprofiloanagrafico.SetAggiornamentoProfiloAnagrafico")
    @ResponseWrapper(localName = "SetAggiornamentoProfiloAnagraficoResponse", targetNamespace = "http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.setaggiornamentoprofiloanagrafico.SetAggiornamentoProfiloAnagraficoResponse")
    public AggiornamentoProfiloAnagraficoRes setAggiornamentoProfiloAnagrafico(
        @WebParam(name = "DatiProfilo", targetNamespace = "http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it")
        AggiornamentoProfiloAnagrafico datiProfilo);

}
