/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.setaggiornamentoprofiloanagrafico;


import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.csi.scerev.scerevserviziesterni.aura.getnumeroassistitiincaricomedico.GetNumeroAssistitiInCaricoMedico_Service;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SetAggiornamentoProfiloAnagrafico", targetNamespace = "http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it")
public class SetAggiornamentoProfiloAnagrafico_Service
    extends Service
{

    private static final URL SETAGGIORNAMENTOPROFILOANAGRAFICO_WSDL_LOCATION = null;
    private final static QName SETAGGIORNAMENTOPROFILOANAGRAFICO_QNAME = new QName("http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it", "SetAggiornamentoProfiloAnagrafico");

//    static {
//        URL url = null;
//        String urlWSDL = "http://10.102.40.77:57772/sanitxens_t1/AURA.WS.setIAggiornamentoProfiloAnagrafico.cls?WSDL";
//        try {
//            URL baseUrl;
//            baseUrl = GetNumeroAssistitiInCaricoMedico_Service.class.getResource(".");
//            url = new URL(baseUrl, urlWSDL);
//        } catch (MalformedURLException e) {
//        }
//        SETAGGIORNAMENTOPROFILOANAGRAFICO_WSDL_LOCATION = url;
//    }
//
//    public SetAggiornamentoProfiloAnagrafico_Service() {
//        super(__getWsdlLocation(), SETAGGIORNAMENTOPROFILOANAGRAFICO_QNAME);
//    }
//
//    public SetAggiornamentoProfiloAnagrafico_Service(WebServiceFeature... features) {
//        super(__getWsdlLocation(), SETAGGIORNAMENTOPROFILOANAGRAFICO_QNAME, features);
//    }

    public SetAggiornamentoProfiloAnagrafico_Service(URL wsdlLocation) {
        super(wsdlLocation, SETAGGIORNAMENTOPROFILOANAGRAFICO_QNAME);
    }

    public SetAggiornamentoProfiloAnagrafico_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SETAGGIORNAMENTOPROFILOANAGRAFICO_QNAME, features);
    }

    public SetAggiornamentoProfiloAnagrafico_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SetAggiornamentoProfiloAnagrafico_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    public SetAggiornamentoProfiloAnagrafico_Service(String string) {
    	 super(__getWsdlLocation(string), SETAGGIORNAMENTOPROFILOANAGRAFICO_QNAME);
	}

	/**
     * 
     * @return
     *     returns SetAggiornamentoProfiloAnagraficoSoap
     */
    @WebEndpoint(name = "SetAggiornamentoProfiloAnagraficoSoap")
    public SetAggiornamentoProfiloAnagraficoSoap getSetAggiornamentoProfiloAnagraficoSoap() {
        return super.getPort(new QName("http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it", "SetAggiornamentoProfiloAnagraficoSoap"), SetAggiornamentoProfiloAnagraficoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SetAggiornamentoProfiloAnagraficoSoap
     */
    @WebEndpoint(name = "SetAggiornamentoProfiloAnagraficoSoap")
    public SetAggiornamentoProfiloAnagraficoSoap getSetAggiornamentoProfiloAnagraficoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://SetAggiornamentoProfiloAnagrafico.central.services.auraws.aura.csi.it", "SetAggiornamentoProfiloAnagraficoSoap"), SetAggiornamentoProfiloAnagraficoSoap.class, features);
    }

    private static URL __getWsdlLocation(String endpoint) {
    	URL baseUrl;
    	URL url = null;
		baseUrl = SetAggiornamentoProfiloAnagrafico.class.getResource(".");
		try {
			url = new URL(baseUrl, endpoint+"?WSDL");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return url;
    }


}
