/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.setinserimentoprofiloanagrafico;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SetInserimentoProfiloAnagraficoSoap", targetNamespace = "http://SetInserimentoProfiloAnagrafico.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SetInserimentoProfiloAnagraficoSoap {


    /**
     * 
     * @param datiProfilo
     * @return
     *     returns it.csi.aura.auraws.services.central.setinserimentoprofiloanagrafico.InserimentoProfiloAnagraficoRes
     */
    @WebMethod(operationName = "SetInserimentoProfiloAnagrafico", action = "http://SetInserimentoProfiloAnagrafico.central.services.auraws.aura.csi.it/AURA.WS.SetInserimentoProfiloAnagrafico.SetInserimentoProfiloAnagrafico")
    @WebResult(name = "SetInserimentoProfiloAnagraficoResult", targetNamespace = "http://SetInserimentoProfiloAnagrafico.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "SetInserimentoProfiloAnagrafico", targetNamespace = "http://SetInserimentoProfiloAnagrafico.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.setinserimentoprofiloanagrafico.SetInserimentoProfiloAnagrafico")
    @ResponseWrapper(localName = "SetInserimentoProfiloAnagraficoResponse", targetNamespace = "http://SetInserimentoProfiloAnagrafico.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.setinserimentoprofiloanagrafico.SetInserimentoProfiloAnagraficoResponse")
    public InserimentoProfiloAnagraficoRes setInserimentoProfiloAnagrafico(
        @WebParam(name = "DatiProfilo", targetNamespace = "http://SetInserimentoProfiloAnagrafico.central.services.auraws.aura.csi.it")
        InserimentoProfiloAnagrafico datiProfilo);

}
