/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevaurabatch.aura.getambito;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetAmbitoSoap", targetNamespace = "http://GetAmbito.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetAmbitoSoap {


    /**
     * 
     * @return
     *     returns it.csi.aura.auraws.services.central.getambito.GetAmbitoResp3
     */
    @WebMethod(operationName = "GetAmbito", action = "http://GetAmbito.central.services.auraws.aura.csi.it/AURA.WS.GetAmbito.GetAmbito")
    @WebResult(name = "GetAmbitoResponseRec", targetNamespace = "http://GetAmbito.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "GetAmbito", targetNamespace = "http://GetAmbito.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.getambito.GetAmbito")
    @ResponseWrapper(localName = "GetAmbitoResponse", targetNamespace = "http://GetAmbito.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.getambito.GetAmbitoResponse")
    public GetAmbitoResp3 getAmbito();

}
