/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.getdistretto;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetDistretto", targetNamespace = "http://GetDistretto.central.services.auraws.aura.csi.it")
public class GetDistretto_Service
    extends Service
{

    private static final URL GETDISTRETTO_WSDL_LOCATION = null;
    private static final WebServiceException GETDISTRETTO_EXCEPTION = new WebServiceException();
    private final static QName GETDISTRETTO_QNAME = new QName("http://GetDistretto.central.services.auraws.aura.csi.it", "GetDistretto");

//    public GetDistretto_Service() {
//        super(__getWsdlLocation(), GETDISTRETTO_QNAME);
//    }
//
//    public GetDistretto_Service(WebServiceFeature... features) {
//        super(__getWsdlLocation(), GETDISTRETTO_QNAME, features);
//    }

    public GetDistretto_Service(URL wsdlLocation) {
        super(wsdlLocation, GETDISTRETTO_QNAME);
    }

    public GetDistretto_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETDISTRETTO_QNAME, features);
    }

    public GetDistretto_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetDistretto_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    public GetDistretto_Service(String string) {
    	super(__getWsdlLocation(string), GETDISTRETTO_QNAME);
	}

	/**
     * 
     * @return
     *     returns GetDistrettoSoap
     */
    @WebEndpoint(name = "GetDistrettoSoap")
    public GetDistrettoSoap getGetDistrettoSoap() {
        return super.getPort(new QName("http://GetDistretto.central.services.auraws.aura.csi.it", "GetDistrettoSoap"), GetDistrettoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetDistrettoSoap
     */
    @WebEndpoint(name = "GetDistrettoSoap")
    public GetDistrettoSoap getGetDistrettoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://GetDistretto.central.services.auraws.aura.csi.it", "GetDistrettoSoap"), GetDistrettoSoap.class, features);
    }

    private static URL __getWsdlLocation(String endpoint) {
    	URL baseUrl;
    	URL url = null;
		baseUrl = GetDistretto_Service.class.getResource(".");
		try {
			url = new URL(baseUrl, endpoint+"?WSDL");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return url;

    }

}
