/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.getnumeroassistitiincaricomedico;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetNumeroAssistitiInCaricoMedicoSoap", targetNamespace = "http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GetNumeroAssistitiInCaricoMedicoSoap {


    /**
     * 
     * @param idAuraMedico
     * @return
     *     returns it.csi.aura.auraws.services.central.getnumeroassistitiincaricomedico.NumeroAssistitiInCaricoMedicoResponse
     */
    @WebMethod(operationName = "GetNumeroAssistitiInCaricoMedico", action = "http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it/AURA.WS.GetNumeroAssistitiInCaricoMedico.GetNumeroAssistitiInCaricoMedico")
    @WebResult(name = "NumeroAssistitiInCaricoMedicoResp", targetNamespace = "http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "GetNumeroAssistitiInCaricoMedico", targetNamespace = "http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.getnumeroassistitiincaricomedico.GetNumeroAssistitiInCaricoMedico")
    @ResponseWrapper(localName = "GetNumeroAssistitiInCaricoMedicoResponse", targetNamespace = "http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it", className = "it.csi.aura.auraws.services.central.getnumeroassistitiincaricomedico.GetNumeroAssistitiInCaricoMedicoResponse")
    public NumeroAssistitiInCaricoMedicoResponse getNumeroAssistitiInCaricoMedico(
        @WebParam(name = "idAuraMedico", targetNamespace = "http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it")
        String idAuraMedico);

}
