/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.scerev.scerevserviziesterni.aura.getnumeroassistitiincaricomedico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import it.csi.scerev.scerevserviziesterni.aura.setinserimentoprofiloanagrafico.SetInserimentoProfiloAnagrafico;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetNumeroAssistitiInCaricoMedico", targetNamespace = "http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it")
public class GetNumeroAssistitiInCaricoMedico_Service
    extends Service
{

    private static final URL GETNUMEROASSISTITIINCARICOMEDICO_WSDL_LOCATION = null;
    private static final WebServiceException GETNUMEROASSISTITIINCARICOMEDICO_EXCEPTION = new WebServiceException();
    private final static QName GETNUMEROASSISTITIINCARICOMEDICO_QNAME = new QName("http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it", "GetNumeroAssistitiInCaricoMedico");

//    static {
//        URL url = null;
//        WebServiceException e = null;
//        try {
//            url = new URL("file:/C:/Users/Administrator/Desktop/AURA-SER-02-GetNumeroAssistitiInCaricoMedico.wsdl");
//        } catch (MalformedURLException ex) {
//            e = new WebServiceException(ex);
//        }
//        GETNUMEROASSISTITIINCARICOMEDICO_WSDL_LOCATION = url;
//        GETNUMEROASSISTITIINCARICOMEDICO_EXCEPTION = e;
//    }
//
//    public GetNumeroAssistitiInCaricoMedico_Service() {
//        super(__getWsdlLocation(), GETNUMEROASSISTITIINCARICOMEDICO_QNAME);
//    }
//
//    public GetNumeroAssistitiInCaricoMedico_Service(WebServiceFeature... features) {
//        super(__getWsdlLocation(), GETNUMEROASSISTITIINCARICOMEDICO_QNAME, features);
//    }

    public GetNumeroAssistitiInCaricoMedico_Service(URL wsdlLocation) {
        super(wsdlLocation, GETNUMEROASSISTITIINCARICOMEDICO_QNAME);
    }

    public GetNumeroAssistitiInCaricoMedico_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETNUMEROASSISTITIINCARICOMEDICO_QNAME, features);
    }

    public GetNumeroAssistitiInCaricoMedico_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetNumeroAssistitiInCaricoMedico_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    public GetNumeroAssistitiInCaricoMedico_Service(String string) {
    	super(__getWsdlLocation(string), GETNUMEROASSISTITIINCARICOMEDICO_QNAME);
	}

	/**
     * 
     * @return
     *     returns GetNumeroAssistitiInCaricoMedicoSoap
     */
    @WebEndpoint(name = "GetNumeroAssistitiInCaricoMedicoSoap")
    public GetNumeroAssistitiInCaricoMedicoSoap getGetNumeroAssistitiInCaricoMedicoSoap() {
        return super.getPort(new QName("http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it", "GetNumeroAssistitiInCaricoMedicoSoap"), GetNumeroAssistitiInCaricoMedicoSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetNumeroAssistitiInCaricoMedicoSoap
     */
    @WebEndpoint(name = "GetNumeroAssistitiInCaricoMedicoSoap")
    public GetNumeroAssistitiInCaricoMedicoSoap getGetNumeroAssistitiInCaricoMedicoSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://GetNumeroAssistitiInCaricoMedico.central.services.auraws.aura.csi.it", "GetNumeroAssistitiInCaricoMedicoSoap"), GetNumeroAssistitiInCaricoMedicoSoap.class, features);
    }

    private static URL __getWsdlLocation(String endpoint) {
    	URL baseUrl;
    	URL url = null;
		baseUrl = GetNumeroAssistitiInCaricoMedico.class.getResource(".");
		try {
			url = new URL(baseUrl, endpoint+"?WSDL");
		} catch (MalformedURLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
        return url;
    }

}
