/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.scerev.scerevbe.enums;

public enum DocumentoTipoEnum {
	CARTA_IDENTITA_FRONTE("1"),
	CARTA_IDENTITA_RETRO("2"),
	CONSENSO_MEDICO("3"),
	DOCUMENTAZIONE_CLINICA_FIRMATA_DIGITALMENTE("4"),
	MODULO_DI_RICHIESTA_FIRMATO_DAL_DELEGANTE("5"),
	RICEVUTA_PRESENTAZIONE_RICHIESTA_PERMESSO_DI_SOGGIORNO("6"),
	COPIA_PERMESSO_DI_SOGGIORNO("7"),
	RICEVUTA_PRESENTAZIONE_RICHIESTA_RINNOVO_PERMESSO_DI_SOGGIORNO("8"),
	DOCUMENTO_COMPROVANTE_SVOLGIMENTO_REGOLARE_ATTIVITA_LAVORATIVA("9"),
	ISCRIZIONE_AL_CENTRO_PER_L_IMPIEGO("10"),
	CARTA_DI_SOGGIONO_O_RICEVUTA_RICHIESTA_DI_RILASCIO("11"),
	COPIA_CONTRATTO_DI_LAVORO_O_AUTOCERTIFICAZIONE("12"),
	CERTIFICATO_ISCRIZIONE_CAMERA_DI_COMMERCIO_O_ALBO_O_ORDINE_PROFESSIONALE("13"),
	ATTESTATO_APERTURA_PIVA_O_APERTURA_POSIZIONE_INPS("14"),
	DOCUMENTO_ATTESTANTE_CESSAZIONE_RAPPORTO_DI_IMPIEGO_E_DURATA("15"),
	ATTESTATO_ISCRIZIONE_CORSO_FORMAZIONE_PROFESSIONALE_O_AUTOCERTIFICAZIONE("16"),
	ATTESTATO_DI_SOGGIORNO_PERMANENTE("17");

    private final String key;

    DocumentoTipoEnum(String key) {
        this.key = key;
    }

    public String getKey() {
        return key;
    }
    
}
